name: technical-assessment-preparation
channels:
  - anaconda
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - exceptiongroup=1.2.0
  - iniconfig=1.1.1
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - packaging=24.1
  - pip=24.2
  - pluggy=1.0.0
  - pytest=7.4.4
  - python=3.10.14
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tomli=2.0.1
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13